import { db } from '../config/firebase.js';

const logFirebaseError = (error) => {
  console.error('[FIREBASE REALTIME DB ERROR]', error);
};

const toDate = (value) => {
  if (!value) {
    return new Date();
  }

  if (value instanceof Date) {
    return value;
  }

  if (typeof value.toDate === 'function') {
    return value.toDate();
  }

  return new Date(value);
};

/**
 * Push a course message to Firebase Realtime Database
 * Structure: /course_chats/{courseId}/messages/{autoGeneratedKey}
 * This is called non-blocking after MySQL save, so errors don't break the API
 */
export const pushCourseMessage = async (courseId, message) => {
  try {
    if (!db) {
      throw new Error('Firebase Realtime Database is not initialized');
    }

    const resolvedCourseId = courseId ?? message?.chats?.course_id ?? message?.course_id;
    const chatId = message?.chat_id;
    const senderUserId = message?.sender_user_id;
    const content = message?.content;
    const sentAt = toDate(message?.sent_at);
    const createdAt = sentAt.toISOString();

    if (!resolvedCourseId || !chatId || !senderUserId || !content) {
      throw new Error('Missing course chat message fields for Realtime DB sync');
    }

    console.log('🔥 pushing to firebase', resolvedCourseId, message.id);

    const ref = db.ref(`course_chats/${resolvedCourseId}/messages`);

    await ref.push({
      id: message.id,
      content: String(content),
      sender_user_id: Number(senderUserId),
      created_at: message.created_at ?? createdAt,
    });

    console.log('✅ Firebase push success');

    return true;
  } catch (error) {
    console.error('❌ Firebase push failed:', error);
    throw error;
  }
};

/**
 * Get course messages from Firebase Realtime Database
 * Returns all messages for a course, sorted by created_at
 */
export const getCourseMessagesFromFirebase = async (courseId) => {
  try {
    if (!db) {
      logFirebaseError(new Error('Firebase Realtime Database is not initialized'));
      return [];
    }

    const snapshot = await db.ref(`course_chats/${courseId}/messages`).get();
    
    if (snapshot.exists()) {
      const messages = [];
      snapshot.forEach((child) => {
        messages.push({
          id: child.key,
          ...child.val(),
        });
      });

      // Sort by created_at ascending (oldest first)
      messages.sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
      
      return messages;
    }

    return [];
  } catch (error) {
    logFirebaseError(error);
    return [];
  }
};