import { generateUsers,addUser,addUserWithGeneratedCredentials,getAllUsers,updateUser,deleteUser, exportOrganizationUsersCredentials, linkParentToStudents } from "../services/userService.js";
import { readExcelFile } from "../utils/readExcelFile.js";
import { validateAddUserData, validateAutoGeneratedUserData, validateExcelData, validateParentStudentLinkData } from "../validations/userValidation.js";
import prisma from "../utils/prisma.js";
import { deleteFromCloudinary, uploadBufferToCloudinary } from "../utils/cloudinaryUpload.js";

const buildDomainFromSubdomain = (subdomain) => {
  const sanitized = String(subdomain || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "");

  if (!sanitized) {
    return null;
  }

  return `${sanitized}.com`;
};

export const generateUsersFromExcel = async (req, res) => {
  let uploadedFile = null;

  try {
    if (!req.file) {
      return res.status(400).json({
        message: "Please upload an Excel file",
      });
    }

    uploadedFile = await uploadBufferToCloudinary(req.file.buffer, {
      folder: "learnova/users/excel",
      resource_type: "raw",
    });

    const data = readExcelFile(req.file.buffer);

    if (!data.length) {
      return res.status(400).json({
        message: "Excel file is empty",
      });
    }

    const organizationId = req.user?.id;

    const { errors, validatedRows } = validateExcelData(data, {
      organizationRole: req.user?.role,
    });

    if (errors.length > 0) {
      await deleteFromCloudinary(uploadedFile.public_id, uploadedFile.resource_type);

      return res.status(422).json({
        message: "Excel validation failed",
        errors,
      });
    }

    // Keep orgId server-side from token and allow optional email/password from Excel.
    const rowsWithOrg = validatedRows.map(({ name, role, age, gender, address, email, password, dob, work, specialization, bio, parentNationalId }) =>
      role === 'STUDENT' || role === 'TEACHER'
        ? { name, role, age, gender, address, email, password, dob, work, specialization, bio, parentNationalId, orgId: organizationId, orgRole: req.user?.role }
        : { name, role, age, gender, address, email, password, dob, work, specialization, bio, parentNationalId }
    );
    const organization = await prisma.organization.findUnique({
      where: { id: organizationId },
      select: { subdomain: true },
    });

    if (!organization) {
      return res.status(404).json({
        message: "Organization not found",
      });
    }

    const domain = buildDomainFromSubdomain(organization.subdomain);

    if (!domain) {
      return res.status(400).json({
        message: "Unable to derive a valid domain from organization subdomain",
      });
    }

    const { createdUsers, createdParents = [], skippedUsers } = await generateUsers(rowsWithOrg, domain);

    return res.status(201).json({
      message: "Users import completed",
      summary: {
        totalRows: validatedRows.length,
        created: createdUsers.length,
        skipped: skippedUsers.length,
      },
      file: {
        url: uploadedFile.url,
        public_id: uploadedFile.public_id,
      },
      users: createdUsers,
      autoCreatedParents: createdParents,
      skipped: skippedUsers,
    });
  } catch (error) {
    console.error(error);

    if (uploadedFile?.public_id) {
      try {
        await deleteFromCloudinary(uploadedFile.public_id, uploadedFile.resource_type);
      } catch (cleanupError) {
        console.error("Cloudinary cleanup failed:", cleanupError.message);
      }
    }

    if (error.message === "Cloudinary environment variables are missing") {
      return res.status(500).json({
        message: "Cloudinary is not configured correctly",
      });
    }

    return res.status(500).json({
      message: "Internal server error",
      error: error.message,
    });
  }
};



export const  addUserController=async (req,res)=>{
  try {
const bodyWithOrg = { ...req.body, orgId: req.user?.id, orgRole: req.user?.role };
const { errors, validatedData } = validateAddUserData(bodyWithOrg);

if (errors.length > 0) {
  return res.status(422).json({
    message: "Validation failed",
    errors,
  });
}

const result=await addUser(validatedData);
 return res.status(201).json({
      message: 'Add new User successfully',
      data: result,
    });
  }catch (error) {
   if (error.message === "user email already exists") {
    return res.status(409).json({ message: error.message });
   }

   return res.status(500).json({message:"Server Error", error: error.message})
  }
 
}

export const createUserWithGeneratedCredentialsController = async (req, res) => {
  try {
    const bodyWithOrg = { ...req.body, orgId: req.user?.id, orgRole: req.user?.role };
    const { errors, validatedData } = validateAutoGeneratedUserData(bodyWithOrg);

    if (errors.length > 0) {
      return res.status(422).json({
        message: "Validation failed",
        errors,
      });
    }

    const organization = await prisma.organization.findUnique({
      where: { id: req.user?.id },
      select: { subdomain: true },
    });

    if (!organization) {
      return res.status(404).json({
        message: "Organization not found",
      });
    }

    const domain = buildDomainFromSubdomain(organization.subdomain);

    if (!domain) {
      return res.status(400).json({
        message: "Unable to derive a valid domain from organization subdomain",
      });
    }

    const result = await addUserWithGeneratedCredentials(validatedData, domain);

    return res.status(201).json({
      message: "Add new User successfully",
      data: result.user,
      credentials: result.credentials,
      parentLinkStatus: result.parentLinkStatus,
    });
  } catch (error) {
    if (error?.code === "P2002") {
      return res.status(409).json({ message: "user email already exists" });
    }
    return res.status(500).json({ message: "Server Error", error: error.message });
  }
};

export const getAllUsersController = async (req, res) => {
  try {
    const users = await getAllUsers(req.user?.id, req.user?.role);
    return res.status(200).json({
      message: 'Users retrieved successfully',
      total: users.length,
      data: users,
    });
  } catch (error) {
    return res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

export const updateUserController = async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (isNaN(id)) {
      return res.status(400).json({ message: 'Invalid user id' });
    }

    const updated = await updateUser(id, req.body, req.user?.id, req.user?.role);
    return res.status(200).json({
      message: 'User updated successfully',
      data: updated,
    });
  } catch (error) {
    if (error.message === 'user not found') {
      return res.status(404).json({ message: error.message });
    }
    if (error.message === 'user email already exists') {
      return res.status(409).json({ message: error.message });
    }
    return res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

export const deleteUserController = async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (isNaN(id)) {
      return res.status(400).json({ message: 'Invalid user id' });
    }

    await deleteUser(id, req.user?.id, req.user?.role);
    return res.status(200).json({ message: 'User deleted successfully' });
  } catch (error) {
    if (error.message === 'user not found') {
      return res.status(404).json({ message: error.message });
    }
    return res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

export const exportUsersCredentialsController = async (req, res) => {
  try {
    const csv = await exportOrganizationUsersCredentials(req.user?.id, req.user?.role);
    const csvWithBom = `\uFEFF${csv}`;
    const dateLabel = new Date().toISOString().slice(0, 10);

    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="organization-users-credentials-${dateLabel}.csv"`);
    return res.status(200).send(csvWithBom);
  } catch (error) {
    return res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

export const linkParentToStudentsController = async (req, res) => {
  try {
    const parentId = Number(req.params.parentId);
    if (!Number.isInteger(parentId) || parentId <= 0) {
      return res.status(400).json({ message: 'Invalid parent id' });
    }

    const orgRole = String(req.user?.role || '').trim().toUpperCase();
    if (orgRole !== 'SCHOOL') {
      return res.status(403).json({ message: 'This operation is only available for SCHOOL organizations' });
    }

    const { errors, validatedData } = validateParentStudentLinkData(req.body);
    if (errors.length > 0) {
      return res.status(422).json({
        message: 'Validation failed',
        errors,
      });
    }

    const result = await linkParentToStudents({
      orgId: req.user?.id,
      orgRole,
      parentId,
      studentIds: validatedData.studentIds,
    });

    return res.status(200).json({
      message: 'Parent linked to students successfully',
      data: result,
    });
  } catch (error) {
    if (error.statusCode) {
      return res.status(error.statusCode).json({ message: error.message });
    }

    return res.status(500).json({ message: 'Server Error', error: error.message });
  }
};